### ISSUE TITLE
docker arm64

### ISSUE THREAD

**Issue by jaonoctus** [ez-org/eznode#18]
Does anyone know how to build it for arm64?

tried 

`docker buildx build --platform linux/amd64,linux/arm64 -t myuser/eznode:latest .`

or

`docker build --platform linux/arm64 -t myuser/eznode:latest .`

but when using the image, I got this error:

```
standard_init_linux.go:228: exec user process caused: exec format error
```

**Comment by shesek** [comment]
There are a few [build args](https://github.com/ez-org/eznode/blob/master/docker/arm64.env) that need to be set to build the image for arm64.

You can set these args and build the docker image by running the following command in the repo directory: `./docker/build-arch.sh arm64 -t eznode`

This is also mentioned on https://ezno.de/building

**Comment by jaonoctus** [comment]
thank you @shesek
