### ISSUE TITLE
Getting bash error installing docker

### ISSUE THREAD

**Issue by kloinka** [ez-org/eznode#7]
running `docker run -it --rm --name ez -v ~/eznode:/data eznode/eznode TOR=1 XPUB=<xpub>` 
results in `bash: syntax error near unexpected token `newline' `

**Comment by shesek** [comment]
The `<xpub>` part is meant to be replaced with your wallet's xpub. There are some instructions for this here: https://ezno.de/packages#bitcoin-wallet-tracker (see "Electrum wallet setup").

You can also start eznode without setting an XPUB if you don't have an handy one, i.e. `docker run -it --rm --name ez -v ~/eznode:/data eznode/eznode TOR=1`. It means that the Electrum server won't report your wallet activity, but everything else will work.
